org: irishfagan
app: njs-export-inventory-tracker
service: njs-export-inventory-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true

functions:
  frameCount:
    handler: handler.frameCount
    events:
      - httpApi:
          path: /frames/count
          method: get
  frames:
    timeout: 60
    handler: handler.frames
    events:
      - s3:
          bucket: njs-inventory
      - httpApi:
          path: /frames
          method: get
  chainrings:
    timeout: 60
    handler: handler.chainrings
    events:
      - httpApi:
          path: /chainrings
          method: get

package:
  exclude:
    - node_modules/**