org: irishfagan
app: njs-export-inventory-tracker
service: njs-export-inventory-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true
  layers:
    - arn:aws:lambda:us-west-2:740451665580:layer:axiosLayer:2

functions:
  frameCount:
    handler: handler.frameCount
    events:
      - httpApi:
          path: /frames/count
          method: get
  frames:
    timeout: 30
    handler: handler.frames
    events:
      - s3:
          bucket: njs-inventory
      - httpApi:
          path: /frames
          method: get
  chainrings:
    timeout: 30
    handler: handler.chainrings
    events:
      - httpApi:
          path: /chainrings
          method: get
  cranks:
    timeout: 30
    handler: handler.cranks
    events:
      - httpApi:
          path: /cranks
          method: get
  hubs:
    timeout: 30
    handler: handler.hubs
    events:
      - httpApi:
          path: /hubs
          method: get
  stems:
    timeout: 30
    handler: handler.stems
    events:
      - httpApi:
          path: /stems
          method: get
  handlebars:
    timeout: 30
    handler: handler.handlebars
    events:
      - httpApi:
          path: /handlebars
          method: get

package:
  exclude:
    - node_modules/**