org: irishfagan
app: njs-export-inventory-tracker
service: njs-export-inventory-tracker
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true
  layers:
    - arn:aws:lambda:us-west-2:740451665580:layer:axiosLayer:2
    - arn:aws:lambda:us-west-2:740451665580:layer:mysql:2
    - arn:aws:lambda:us-west-2:740451665580:layer:crypto-js:2
  timeout: 29
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:BatchWriteItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:DeleteItem'
          Resource: '*'
        - Effect: Allow
          Action: 
            - 's3:putObject'
            - 's3:getObject'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource: '*'

functions:
  unsubscribe:
    handler: handler.unsubscribe
    events:
      - http:
          path: unsubscribe/
          method: GET
          request:
            parameters:
              querystrings:
                email: true
                keywords: true
                hash: true
  unsubscribeConfirm:
    handler: handler.unsubscribeConfirm
    events:
      - http:
          path: unsubscribe/confirm/
          method: GET
          request:
            parameters:
              email: true
              keywords: true
  subscribe:
    handler: handler.subscribe
    events:
      - http:
          path: subscribe
          method: GET
          request:
            parameters:
              querystrings:
                hash: true
                keywords: true
                email: true
  getKeywords:
    handler: handler.getKeywords
    events:
      - http:
          path: get/keywords/
          method: GET
          request:
            parameters:
              querystrings:
                email: true
  sendEmailConfirmation:
    handler: handler.sendEmailConfirmation
    events:
      - http:
          path: update/
          method: POST
          integration: lambda
          cors: true
  getLatestListingDate:
    handler: handler.getLatestListingDate
    events:
      - httpApi:
          path: /latest
          method: get
    timeout: 25
  uploadAllComponents:
    handler: handler.uploadAllComponents
    events:
      - httpApi:
          path: /upload
          method: GET
      - s3:
          bucket: 'njs-export'
          event: s3:ObjectCreated:*
          rules:
            - prefix: products/
            - suffix: .json
          existing: true
    maximumRetryAttempts: 2
  getComponentsByDate:
    handler: handler.getComponentsByDate
    events:
      - http:
          path: get/
          method: GET
          request:
            parameters:
              querystrings:
                date: true
  checkKeywordSubscription:
    handler: handler.checkKeywordSubscription
    events:
      - stream:
          arn: arn:aws:dynamodb:us-west-2:740451665580:table/NJS-ExportInventory/stream/2022-11-11T20:28:38.331
          startingPosition: LATEST
          maximumRetryAttempts: 5
          enabled: true
  checkNewComponents:
    handler: handler.checkNewComponents
    events:
      - schedule: rate(1 hour)

resources:
  Resources:
    UserHashTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserHashTable
        AttributeDefinitions:
          - AttributeName: UserHash
            AttributeType: N
          - AttributeName: ttl
            AttributeType: N
        KeySchema:
          - AttributeName: UserHash
            KeyType: HASH
          - AttributeName: ttl
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: userHashIndex
            KeySchema:
              - AttributeName: UserHash
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    NJSExportInventory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NJS-ExportInventory
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: N
          - AttributeName: Type
            AttributeType: S
          - AttributeName: CreatedDate
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
        GlobalSecondaryIndexes:
          - IndexName: componentTypeIndex
            KeySchema:
              - AttributeName: Type
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 2
          - IndexName: createdDateIndex
            KeySchema:
              - AttributeName: CreatedDate
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 2

package:
  exclude:
    - node_modules/**