org: irishfagan
app: njs-export-inventory-tracker
service: njs-export-inventory-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  manageFrameInventory:
    handler: handler.manageFrameInventory
    events:
      - s3:
        bucket: njs-inventory
      - httpApi:
          path: /frames
          method: get
          cors: true

package:
  exclude:
    - node_modules/**