org: irishfagan
app: njs-export-inventory-tracker
service: njs-export-inventory-tracker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true
  layers:
    - arn:aws:lambda:us-west-2:740451665580:layer:axiosLayer:2
  timeout: 25
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:Query'
          Resource: '*'

functions:
  frameCount:
    handler: handler.frameCount
    events:
      - httpApi:
          path: /frames/count
          method: get
    timeout: 25
  latestListing:
    handler: handler.latestListing
    events:
      - httpApi:
          path: /latest
          method: get
    timeout: 25
  frames:
    handler: handler.frames
    events:
      - httpApi:
          path: /frames
          method: get
    timeout: 25
    environment: 
      BUCKET: njs-export
      REGION: us-west-2
  forks:
    handler: handler.forks
    events:
      - httpApi:
          path: /forks
          method: get
    timeout: 25
  cranks:
    handler: handler.cranks
    events:
      - httpApi:
          path: /cranks
          method: get
    timeout: 25
  chainrings:
    handler: handler.chainrings
    events:
      - httpApi:
          path: /chainrings
          method: get
    timeout: 25
  cogs:
    handler: handler.cogs
    events:
      - httpApi:
          path: /cogs
          method: get
    timeout: 25
  chains:
    handler: handler.chains
    events:
      - httpApi:
          path: /chains
          method: get
    timeout: 25
  stems:
    handler: handler.stems
    events:
      - httpApi:
          path: /stems
          method: get
    timeout: 25
  handlebars:
    handler: handler.handlebars
    events:
      - httpApi:
          path: /handlebars
          method: get
    timeout: 25
  seatposts:
    handler: handler.seatposts
    events:
      - httpApi:
          path: /seatposts
          method: get
    timeout: 25
  saddles:
    handler: handler.saddles
    events:
      - httpApi:
          path: /saddles
          method: get
    timeout: 25
  wheels:
    handler: handler.wheels
    events:
      - httpApi:
          path: /wheelsets
          method: get
    timeout: 25
  hubs:
    handler: handler.hubs
    events:
      - httpApi:
          path: /hubs
          method: get
    timeout: 25
  rims:
    handler: handler.rims
    events:
      - httpApi:
          path: /rims
          method: get
    timeout: 25
  uploadComponents:
    handler: handler.uploadComponents
    events:
      - http:
          path: upload
          method: POST
  getComponents:
    handler: handler.getComponents
    events:
      - http:
          path: get/
          method: GET
          request:
            parameters:
              querystrings:
                date: true

resources:
  Resources:
    NJSExportInventory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NJSExportInventory
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: N
          - AttributeName: Type
            AttributeType: S
          - AttributeName: CreatedDate
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: componentTypeIndex
            KeySchema:
              - AttributeName: Type
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: createdDateIndex
            KeySchema:
              - AttributeName: CreatedDate
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

package:
  exclude:
    - node_modules/**